# Site settings
title: Lauren Barker
subtitle: Github Pages
email: 
description: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "lbarker.github.io" # the base hostname & protocol for your site
author:
street_address: 
city: 
state: 
zip_code: 
country: United States of America
phone: 
permalink: /:categories/:year/:title/
# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 3
tiles-count-news: 6


# Social settings
500px_url:
facebook_url: 
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 
youtube_url: 

# Build settings
markdown: kramdown

sass:
  style: compressed
  sass_dir: _sass

gems:
  - jekyll-redirect-from

